server:
  # Dùng biến môi trường PORT nếu có (Railway cấp), nếu không thì dùng 8080
  port: ${PORT:8080}

spring:
  datasource:
    # Cấu hình kết nối tới Somee
    url: jdbc:sqlserver://dgkongu.mssql.somee.com;databaseName=dgkongu;encrypt=true;trustServerCertificate=true;
    username: DgKoNgu_SQLLogin_1
    # --- QUAN TRỌNG: Thay mật khẩu bạn đã tạo ở Somee vào đây ---
    password: "4i2kepqbee"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

  # Giữ nguyên cấu hình Mail của bạn
  mail:
    host: smtp.gmail.com
    port: 587
    username: duongchu868@gmail.com
    password: "azgl tbvt dgkw qqel"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# --- LƯU Ý QUAN TRỌNG VỀ ĐƯỜNG DẪN FILE ---
file:
  # KHÔNG ĐƯỢC để đường dẫn C:\\Users... vì Server là Linux, không có ổ C.
  # Đặt là "uploads" để nó tạo thư mục ngay trong project
  upload-dir: "uploads"